version: "3"
services:
  jenkins:
    build: 
      context: ./config
    container_name: jenkins
    env_file:
      - .env
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - jenkins_home:/var/jenkins_home